language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install -y slapd libldap2-dev"
  - "pip install -r requirements.txt"
script: "python -m unittest -v tests"
